title: Q's Data Analyst Portfolio
logo: assets/img/pro_pic.png
#description: text below img
show_downloads: False
theme: jekyll-theme-minimal
description: Welcome to my Data Analyst portfolio! This repository contains three data analysis projects from different industries: Lego, Pharma, and Fintech. Each project includes data acquisition, data preparation, data analytics, and data visualization using Python.
